# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: franka_trial.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'franka_trial.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ranka_trial.proto\"7\n\x0cTrialRequest\x12\x10\n\x08trial_id\x18\x01 \x01(\t\x12\x15\n\rtrialDuration\x18\x02 \x01(\x01\"r\n\x13TrialResponseStream\x12*\n\x0cstatusUpdate\x18\x01 \x01(\x0b\x32\x12.TrialStatusUpdateH\x00\x12$\n\tdataPoint\x18\x02 \x01(\x0b\x32\x0f.TrialDataPointH\x00\x42\t\n\x07payload\"B\n\x11TrialStatusUpdate\x12\x1c\n\x06status\x18\x01 \x01(\x0e\x32\x0c.TrialStatus\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x7f\n\x0eTrialDataPoint\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12 \n\x0e\x64\x65vicePosition\x18\x02 \x01(\x0b\x32\x08.Vector3\x12\x1f\n\rproxyPosition\x18\x03 \x01(\x0b\x32\x08.Vector3\x12\x17\n\x05\x66orce\x18\x04 \x01(\x0b\x32\x08.Vector3\"(\n\x05\x43olor\x12\t\n\x01r\x18\x01 \x01(\x01\x12\t\n\x01g\x18\x02 \x01(\x01\x12\t\n\x01\x62\x18\x03 \x01(\x01\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01*4\n\x0bTrialStatus\x12\x0b\n\x07STARTED\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x32G\n\x12\x46rankaTrialService\x12\x31\n\x08RunTrial\x12\r.TrialRequest\x1a\x14.TrialResponseStream0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'franka_trial_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRIALSTATUS']._serialized_start=478
  _globals['_TRIALSTATUS']._serialized_end=530
  _globals['_TRIALREQUEST']._serialized_start=22
  _globals['_TRIALREQUEST']._serialized_end=77
  _globals['_TRIALRESPONSESTREAM']._serialized_start=79
  _globals['_TRIALRESPONSESTREAM']._serialized_end=193
  _globals['_TRIALSTATUSUPDATE']._serialized_start=195
  _globals['_TRIALSTATUSUPDATE']._serialized_end=261
  _globals['_TRIALDATAPOINT']._serialized_start=263
  _globals['_TRIALDATAPOINT']._serialized_end=390
  _globals['_COLOR']._serialized_start=392
  _globals['_COLOR']._serialized_end=432
  _globals['_VECTOR3']._serialized_start=434
  _globals['_VECTOR3']._serialized_end=476
  _globals['_FRANKATRIALSERVICE']._serialized_start=532
  _globals['_FRANKATRIALSERVICE']._serialized_end=603
# @@protoc_insertion_point(module_scope)
