syntax = "proto3";

service FrankaTrialService {
    rpc RunTrial(TrialRequest) returns (stream TrialResponseStream);
}

// Message structure for client trial requests
message TrialRequest {
    string trial_id = 1;
    double trialDuration = 2;
}

// Message structure for server responses (in a stream)
message TrialResponseStream {
    /* Each response message in the stream is either a status update to be displayed
    or a data point to be logged to the CSV file on Python client */
    oneof payload {
        TrialStatusUpdate statusUpdate = 1;
        TrialDataPoint dataPoint = 2;
    }
}

// Response data structures
message TrialStatusUpdate {
    TrialStatus status = 1;
    string message = 2;
}

enum TrialStatus {
    STARTED = 0;
    ERROR = 1;
    COMPLETED = 2;
}

message TrialDataPoint {
    double timestamp = 1;
    Vector3 devicePosition = 2;
    Vector3 proxyPosition = 3;
    Vector3 force = 4;
}

// Utility data structures
message Color {
    double r = 1;
    double g = 2;
    double b = 3;
}

message Vector3 {
    double x = 1;
    double y = 2;
    double z = 3;
}