// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: franka_trial.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_franka_5ftrial_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_franka_5ftrial_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_franka_5ftrial_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_franka_5ftrial_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_franka_5ftrial_2eproto;
class Color;
struct ColorDefaultTypeInternal;
extern ColorDefaultTypeInternal _Color_default_instance_;
class TrialDataPoint;
struct TrialDataPointDefaultTypeInternal;
extern TrialDataPointDefaultTypeInternal _TrialDataPoint_default_instance_;
class TrialRequest;
struct TrialRequestDefaultTypeInternal;
extern TrialRequestDefaultTypeInternal _TrialRequest_default_instance_;
class TrialResponseStream;
struct TrialResponseStreamDefaultTypeInternal;
extern TrialResponseStreamDefaultTypeInternal _TrialResponseStream_default_instance_;
class TrialStatusUpdate;
struct TrialStatusUpdateDefaultTypeInternal;
extern TrialStatusUpdateDefaultTypeInternal _TrialStatusUpdate_default_instance_;
class Vector3;
struct Vector3DefaultTypeInternal;
extern Vector3DefaultTypeInternal _Vector3_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Color* Arena::CreateMaybeMessage<::Color>(Arena*);
template<> ::TrialDataPoint* Arena::CreateMaybeMessage<::TrialDataPoint>(Arena*);
template<> ::TrialRequest* Arena::CreateMaybeMessage<::TrialRequest>(Arena*);
template<> ::TrialResponseStream* Arena::CreateMaybeMessage<::TrialResponseStream>(Arena*);
template<> ::TrialStatusUpdate* Arena::CreateMaybeMessage<::TrialStatusUpdate>(Arena*);
template<> ::Vector3* Arena::CreateMaybeMessage<::Vector3>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum TrialStatus : int {
  STARTED = 0,
  ERROR = 1,
  COMPLETED = 2,
  TrialStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  TrialStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool TrialStatus_IsValid(int value);
constexpr TrialStatus TrialStatus_MIN = STARTED;
constexpr TrialStatus TrialStatus_MAX = COMPLETED;
constexpr int TrialStatus_ARRAYSIZE = TrialStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TrialStatus_descriptor();
template<typename T>
inline const std::string& TrialStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TrialStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TrialStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TrialStatus_descriptor(), enum_t_value);
}
inline bool TrialStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, TrialStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TrialStatus>(
    TrialStatus_descriptor(), name, value);
}
// ===================================================================

class TrialRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TrialRequest) */ {
 public:
  inline TrialRequest() : TrialRequest(nullptr) {}
  ~TrialRequest() override;
  explicit PROTOBUF_CONSTEXPR TrialRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TrialRequest(const TrialRequest& from);
  TrialRequest(TrialRequest&& from) noexcept
    : TrialRequest() {
    *this = ::std::move(from);
  }

  inline TrialRequest& operator=(const TrialRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrialRequest& operator=(TrialRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrialRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const TrialRequest* internal_default_instance() {
    return reinterpret_cast<const TrialRequest*>(
               &_TrialRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TrialRequest& a, TrialRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(TrialRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrialRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrialRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TrialRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TrialRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TrialRequest& from) {
    TrialRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrialRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TrialRequest";
  }
  protected:
  explicit TrialRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTrialIdFieldNumber = 1,
    kTrialDurationFieldNumber = 2,
  };
  // string trial_id = 1;
  void clear_trial_id();
  const std::string& trial_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_trial_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_trial_id();
  PROTOBUF_NODISCARD std::string* release_trial_id();
  void set_allocated_trial_id(std::string* trial_id);
  private:
  const std::string& _internal_trial_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_trial_id(const std::string& value);
  std::string* _internal_mutable_trial_id();
  public:

  // double trialDuration = 2;
  void clear_trialduration();
  double trialduration() const;
  void set_trialduration(double value);
  private:
  double _internal_trialduration() const;
  void _internal_set_trialduration(double value);
  public:

  // @@protoc_insertion_point(class_scope:TrialRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr trial_id_;
    double trialduration_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_franka_5ftrial_2eproto;
};
// -------------------------------------------------------------------

class TrialResponseStream final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TrialResponseStream) */ {
 public:
  inline TrialResponseStream() : TrialResponseStream(nullptr) {}
  ~TrialResponseStream() override;
  explicit PROTOBUF_CONSTEXPR TrialResponseStream(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TrialResponseStream(const TrialResponseStream& from);
  TrialResponseStream(TrialResponseStream&& from) noexcept
    : TrialResponseStream() {
    *this = ::std::move(from);
  }

  inline TrialResponseStream& operator=(const TrialResponseStream& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrialResponseStream& operator=(TrialResponseStream&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrialResponseStream& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kStatusUpdate = 1,
    kDataPoint = 2,
    PAYLOAD_NOT_SET = 0,
  };

  static inline const TrialResponseStream* internal_default_instance() {
    return reinterpret_cast<const TrialResponseStream*>(
               &_TrialResponseStream_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TrialResponseStream& a, TrialResponseStream& b) {
    a.Swap(&b);
  }
  inline void Swap(TrialResponseStream* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrialResponseStream* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrialResponseStream* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TrialResponseStream>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TrialResponseStream& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TrialResponseStream& from) {
    TrialResponseStream::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrialResponseStream* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TrialResponseStream";
  }
  protected:
  explicit TrialResponseStream(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusUpdateFieldNumber = 1,
    kDataPointFieldNumber = 2,
  };
  // .TrialStatusUpdate statusUpdate = 1;
  bool has_statusupdate() const;
  private:
  bool _internal_has_statusupdate() const;
  public:
  void clear_statusupdate();
  const ::TrialStatusUpdate& statusupdate() const;
  PROTOBUF_NODISCARD ::TrialStatusUpdate* release_statusupdate();
  ::TrialStatusUpdate* mutable_statusupdate();
  void set_allocated_statusupdate(::TrialStatusUpdate* statusupdate);
  private:
  const ::TrialStatusUpdate& _internal_statusupdate() const;
  ::TrialStatusUpdate* _internal_mutable_statusupdate();
  public:
  void unsafe_arena_set_allocated_statusupdate(
      ::TrialStatusUpdate* statusupdate);
  ::TrialStatusUpdate* unsafe_arena_release_statusupdate();

  // .TrialDataPoint dataPoint = 2;
  bool has_datapoint() const;
  private:
  bool _internal_has_datapoint() const;
  public:
  void clear_datapoint();
  const ::TrialDataPoint& datapoint() const;
  PROTOBUF_NODISCARD ::TrialDataPoint* release_datapoint();
  ::TrialDataPoint* mutable_datapoint();
  void set_allocated_datapoint(::TrialDataPoint* datapoint);
  private:
  const ::TrialDataPoint& _internal_datapoint() const;
  ::TrialDataPoint* _internal_mutable_datapoint();
  public:
  void unsafe_arena_set_allocated_datapoint(
      ::TrialDataPoint* datapoint);
  ::TrialDataPoint* unsafe_arena_release_datapoint();

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:TrialResponseStream)
 private:
  class _Internal;
  void set_has_statusupdate();
  void set_has_datapoint();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::TrialStatusUpdate* statusupdate_;
      ::TrialDataPoint* datapoint_;
    } payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_franka_5ftrial_2eproto;
};
// -------------------------------------------------------------------

class TrialStatusUpdate final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TrialStatusUpdate) */ {
 public:
  inline TrialStatusUpdate() : TrialStatusUpdate(nullptr) {}
  ~TrialStatusUpdate() override;
  explicit PROTOBUF_CONSTEXPR TrialStatusUpdate(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TrialStatusUpdate(const TrialStatusUpdate& from);
  TrialStatusUpdate(TrialStatusUpdate&& from) noexcept
    : TrialStatusUpdate() {
    *this = ::std::move(from);
  }

  inline TrialStatusUpdate& operator=(const TrialStatusUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrialStatusUpdate& operator=(TrialStatusUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrialStatusUpdate& default_instance() {
    return *internal_default_instance();
  }
  static inline const TrialStatusUpdate* internal_default_instance() {
    return reinterpret_cast<const TrialStatusUpdate*>(
               &_TrialStatusUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(TrialStatusUpdate& a, TrialStatusUpdate& b) {
    a.Swap(&b);
  }
  inline void Swap(TrialStatusUpdate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrialStatusUpdate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrialStatusUpdate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TrialStatusUpdate>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TrialStatusUpdate& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TrialStatusUpdate& from) {
    TrialStatusUpdate::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrialStatusUpdate* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TrialStatusUpdate";
  }
  protected:
  explicit TrialStatusUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // .TrialStatus status = 1;
  void clear_status();
  ::TrialStatus status() const;
  void set_status(::TrialStatus value);
  private:
  ::TrialStatus _internal_status() const;
  void _internal_set_status(::TrialStatus value);
  public:

  // @@protoc_insertion_point(class_scope:TrialStatusUpdate)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    int status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_franka_5ftrial_2eproto;
};
// -------------------------------------------------------------------

class TrialDataPoint final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TrialDataPoint) */ {
 public:
  inline TrialDataPoint() : TrialDataPoint(nullptr) {}
  ~TrialDataPoint() override;
  explicit PROTOBUF_CONSTEXPR TrialDataPoint(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TrialDataPoint(const TrialDataPoint& from);
  TrialDataPoint(TrialDataPoint&& from) noexcept
    : TrialDataPoint() {
    *this = ::std::move(from);
  }

  inline TrialDataPoint& operator=(const TrialDataPoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrialDataPoint& operator=(TrialDataPoint&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrialDataPoint& default_instance() {
    return *internal_default_instance();
  }
  static inline const TrialDataPoint* internal_default_instance() {
    return reinterpret_cast<const TrialDataPoint*>(
               &_TrialDataPoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(TrialDataPoint& a, TrialDataPoint& b) {
    a.Swap(&b);
  }
  inline void Swap(TrialDataPoint* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrialDataPoint* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrialDataPoint* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TrialDataPoint>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TrialDataPoint& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TrialDataPoint& from) {
    TrialDataPoint::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrialDataPoint* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TrialDataPoint";
  }
  protected:
  explicit TrialDataPoint(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDevicePositionFieldNumber = 2,
    kProxyPositionFieldNumber = 3,
    kForceFieldNumber = 4,
    kTimestampFieldNumber = 1,
  };
  // .Vector3 devicePosition = 2;
  bool has_deviceposition() const;
  private:
  bool _internal_has_deviceposition() const;
  public:
  void clear_deviceposition();
  const ::Vector3& deviceposition() const;
  PROTOBUF_NODISCARD ::Vector3* release_deviceposition();
  ::Vector3* mutable_deviceposition();
  void set_allocated_deviceposition(::Vector3* deviceposition);
  private:
  const ::Vector3& _internal_deviceposition() const;
  ::Vector3* _internal_mutable_deviceposition();
  public:
  void unsafe_arena_set_allocated_deviceposition(
      ::Vector3* deviceposition);
  ::Vector3* unsafe_arena_release_deviceposition();

  // .Vector3 proxyPosition = 3;
  bool has_proxyposition() const;
  private:
  bool _internal_has_proxyposition() const;
  public:
  void clear_proxyposition();
  const ::Vector3& proxyposition() const;
  PROTOBUF_NODISCARD ::Vector3* release_proxyposition();
  ::Vector3* mutable_proxyposition();
  void set_allocated_proxyposition(::Vector3* proxyposition);
  private:
  const ::Vector3& _internal_proxyposition() const;
  ::Vector3* _internal_mutable_proxyposition();
  public:
  void unsafe_arena_set_allocated_proxyposition(
      ::Vector3* proxyposition);
  ::Vector3* unsafe_arena_release_proxyposition();

  // .Vector3 force = 4;
  bool has_force() const;
  private:
  bool _internal_has_force() const;
  public:
  void clear_force();
  const ::Vector3& force() const;
  PROTOBUF_NODISCARD ::Vector3* release_force();
  ::Vector3* mutable_force();
  void set_allocated_force(::Vector3* force);
  private:
  const ::Vector3& _internal_force() const;
  ::Vector3* _internal_mutable_force();
  public:
  void unsafe_arena_set_allocated_force(
      ::Vector3* force);
  ::Vector3* unsafe_arena_release_force();

  // double timestamp = 1;
  void clear_timestamp();
  double timestamp() const;
  void set_timestamp(double value);
  private:
  double _internal_timestamp() const;
  void _internal_set_timestamp(double value);
  public:

  // @@protoc_insertion_point(class_scope:TrialDataPoint)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Vector3* deviceposition_;
    ::Vector3* proxyposition_;
    ::Vector3* force_;
    double timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_franka_5ftrial_2eproto;
};
// -------------------------------------------------------------------

class Color final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Color) */ {
 public:
  inline Color() : Color(nullptr) {}
  ~Color() override;
  explicit PROTOBUF_CONSTEXPR Color(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Color(const Color& from);
  Color(Color&& from) noexcept
    : Color() {
    *this = ::std::move(from);
  }

  inline Color& operator=(const Color& from) {
    CopyFrom(from);
    return *this;
  }
  inline Color& operator=(Color&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Color& default_instance() {
    return *internal_default_instance();
  }
  static inline const Color* internal_default_instance() {
    return reinterpret_cast<const Color*>(
               &_Color_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Color& a, Color& b) {
    a.Swap(&b);
  }
  inline void Swap(Color* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Color* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Color* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Color>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Color& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Color& from) {
    Color::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Color* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Color";
  }
  protected:
  explicit Color(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRFieldNumber = 1,
    kGFieldNumber = 2,
    kBFieldNumber = 3,
  };
  // double r = 1;
  void clear_r();
  double r() const;
  void set_r(double value);
  private:
  double _internal_r() const;
  void _internal_set_r(double value);
  public:

  // double g = 2;
  void clear_g();
  double g() const;
  void set_g(double value);
  private:
  double _internal_g() const;
  void _internal_set_g(double value);
  public:

  // double b = 3;
  void clear_b();
  double b() const;
  void set_b(double value);
  private:
  double _internal_b() const;
  void _internal_set_b(double value);
  public:

  // @@protoc_insertion_point(class_scope:Color)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double r_;
    double g_;
    double b_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_franka_5ftrial_2eproto;
};
// -------------------------------------------------------------------

class Vector3 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Vector3) */ {
 public:
  inline Vector3() : Vector3(nullptr) {}
  ~Vector3() override;
  explicit PROTOBUF_CONSTEXPR Vector3(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vector3(const Vector3& from);
  Vector3(Vector3&& from) noexcept
    : Vector3() {
    *this = ::std::move(from);
  }

  inline Vector3& operator=(const Vector3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector3& operator=(Vector3&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vector3& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vector3* internal_default_instance() {
    return reinterpret_cast<const Vector3*>(
               &_Vector3_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Vector3& a, Vector3& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector3* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vector3* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vector3* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Vector3>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Vector3& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Vector3& from) {
    Vector3::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector3* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Vector3";
  }
  protected:
  explicit Vector3(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double z = 3;
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // @@protoc_insertion_point(class_scope:Vector3)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double x_;
    double y_;
    double z_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_franka_5ftrial_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TrialRequest

// string trial_id = 1;
inline void TrialRequest::clear_trial_id() {
  _impl_.trial_id_.ClearToEmpty();
}
inline const std::string& TrialRequest::trial_id() const {
  // @@protoc_insertion_point(field_get:TrialRequest.trial_id)
  return _internal_trial_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TrialRequest::set_trial_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.trial_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TrialRequest.trial_id)
}
inline std::string* TrialRequest::mutable_trial_id() {
  std::string* _s = _internal_mutable_trial_id();
  // @@protoc_insertion_point(field_mutable:TrialRequest.trial_id)
  return _s;
}
inline const std::string& TrialRequest::_internal_trial_id() const {
  return _impl_.trial_id_.Get();
}
inline void TrialRequest::_internal_set_trial_id(const std::string& value) {
  
  _impl_.trial_id_.Set(value, GetArenaForAllocation());
}
inline std::string* TrialRequest::_internal_mutable_trial_id() {
  
  return _impl_.trial_id_.Mutable(GetArenaForAllocation());
}
inline std::string* TrialRequest::release_trial_id() {
  // @@protoc_insertion_point(field_release:TrialRequest.trial_id)
  return _impl_.trial_id_.Release();
}
inline void TrialRequest::set_allocated_trial_id(std::string* trial_id) {
  if (trial_id != nullptr) {
    
  } else {
    
  }
  _impl_.trial_id_.SetAllocated(trial_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.trial_id_.IsDefault()) {
    _impl_.trial_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TrialRequest.trial_id)
}

// double trialDuration = 2;
inline void TrialRequest::clear_trialduration() {
  _impl_.trialduration_ = 0;
}
inline double TrialRequest::_internal_trialduration() const {
  return _impl_.trialduration_;
}
inline double TrialRequest::trialduration() const {
  // @@protoc_insertion_point(field_get:TrialRequest.trialDuration)
  return _internal_trialduration();
}
inline void TrialRequest::_internal_set_trialduration(double value) {
  
  _impl_.trialduration_ = value;
}
inline void TrialRequest::set_trialduration(double value) {
  _internal_set_trialduration(value);
  // @@protoc_insertion_point(field_set:TrialRequest.trialDuration)
}

// -------------------------------------------------------------------

// TrialResponseStream

// .TrialStatusUpdate statusUpdate = 1;
inline bool TrialResponseStream::_internal_has_statusupdate() const {
  return payload_case() == kStatusUpdate;
}
inline bool TrialResponseStream::has_statusupdate() const {
  return _internal_has_statusupdate();
}
inline void TrialResponseStream::set_has_statusupdate() {
  _impl_._oneof_case_[0] = kStatusUpdate;
}
inline void TrialResponseStream::clear_statusupdate() {
  if (_internal_has_statusupdate()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.statusupdate_;
    }
    clear_has_payload();
  }
}
inline ::TrialStatusUpdate* TrialResponseStream::release_statusupdate() {
  // @@protoc_insertion_point(field_release:TrialResponseStream.statusUpdate)
  if (_internal_has_statusupdate()) {
    clear_has_payload();
    ::TrialStatusUpdate* temp = _impl_.payload_.statusupdate_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.statusupdate_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::TrialStatusUpdate& TrialResponseStream::_internal_statusupdate() const {
  return _internal_has_statusupdate()
      ? *_impl_.payload_.statusupdate_
      : reinterpret_cast< ::TrialStatusUpdate&>(::_TrialStatusUpdate_default_instance_);
}
inline const ::TrialStatusUpdate& TrialResponseStream::statusupdate() const {
  // @@protoc_insertion_point(field_get:TrialResponseStream.statusUpdate)
  return _internal_statusupdate();
}
inline ::TrialStatusUpdate* TrialResponseStream::unsafe_arena_release_statusupdate() {
  // @@protoc_insertion_point(field_unsafe_arena_release:TrialResponseStream.statusUpdate)
  if (_internal_has_statusupdate()) {
    clear_has_payload();
    ::TrialStatusUpdate* temp = _impl_.payload_.statusupdate_;
    _impl_.payload_.statusupdate_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void TrialResponseStream::unsafe_arena_set_allocated_statusupdate(::TrialStatusUpdate* statusupdate) {
  clear_payload();
  if (statusupdate) {
    set_has_statusupdate();
    _impl_.payload_.statusupdate_ = statusupdate;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:TrialResponseStream.statusUpdate)
}
inline ::TrialStatusUpdate* TrialResponseStream::_internal_mutable_statusupdate() {
  if (!_internal_has_statusupdate()) {
    clear_payload();
    set_has_statusupdate();
    _impl_.payload_.statusupdate_ = CreateMaybeMessage< ::TrialStatusUpdate >(GetArenaForAllocation());
  }
  return _impl_.payload_.statusupdate_;
}
inline ::TrialStatusUpdate* TrialResponseStream::mutable_statusupdate() {
  ::TrialStatusUpdate* _msg = _internal_mutable_statusupdate();
  // @@protoc_insertion_point(field_mutable:TrialResponseStream.statusUpdate)
  return _msg;
}

// .TrialDataPoint dataPoint = 2;
inline bool TrialResponseStream::_internal_has_datapoint() const {
  return payload_case() == kDataPoint;
}
inline bool TrialResponseStream::has_datapoint() const {
  return _internal_has_datapoint();
}
inline void TrialResponseStream::set_has_datapoint() {
  _impl_._oneof_case_[0] = kDataPoint;
}
inline void TrialResponseStream::clear_datapoint() {
  if (_internal_has_datapoint()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.datapoint_;
    }
    clear_has_payload();
  }
}
inline ::TrialDataPoint* TrialResponseStream::release_datapoint() {
  // @@protoc_insertion_point(field_release:TrialResponseStream.dataPoint)
  if (_internal_has_datapoint()) {
    clear_has_payload();
    ::TrialDataPoint* temp = _impl_.payload_.datapoint_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.datapoint_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::TrialDataPoint& TrialResponseStream::_internal_datapoint() const {
  return _internal_has_datapoint()
      ? *_impl_.payload_.datapoint_
      : reinterpret_cast< ::TrialDataPoint&>(::_TrialDataPoint_default_instance_);
}
inline const ::TrialDataPoint& TrialResponseStream::datapoint() const {
  // @@protoc_insertion_point(field_get:TrialResponseStream.dataPoint)
  return _internal_datapoint();
}
inline ::TrialDataPoint* TrialResponseStream::unsafe_arena_release_datapoint() {
  // @@protoc_insertion_point(field_unsafe_arena_release:TrialResponseStream.dataPoint)
  if (_internal_has_datapoint()) {
    clear_has_payload();
    ::TrialDataPoint* temp = _impl_.payload_.datapoint_;
    _impl_.payload_.datapoint_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void TrialResponseStream::unsafe_arena_set_allocated_datapoint(::TrialDataPoint* datapoint) {
  clear_payload();
  if (datapoint) {
    set_has_datapoint();
    _impl_.payload_.datapoint_ = datapoint;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:TrialResponseStream.dataPoint)
}
inline ::TrialDataPoint* TrialResponseStream::_internal_mutable_datapoint() {
  if (!_internal_has_datapoint()) {
    clear_payload();
    set_has_datapoint();
    _impl_.payload_.datapoint_ = CreateMaybeMessage< ::TrialDataPoint >(GetArenaForAllocation());
  }
  return _impl_.payload_.datapoint_;
}
inline ::TrialDataPoint* TrialResponseStream::mutable_datapoint() {
  ::TrialDataPoint* _msg = _internal_mutable_datapoint();
  // @@protoc_insertion_point(field_mutable:TrialResponseStream.dataPoint)
  return _msg;
}

inline bool TrialResponseStream::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void TrialResponseStream::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline TrialResponseStream::PayloadCase TrialResponseStream::payload_case() const {
  return TrialResponseStream::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// TrialStatusUpdate

// .TrialStatus status = 1;
inline void TrialStatusUpdate::clear_status() {
  _impl_.status_ = 0;
}
inline ::TrialStatus TrialStatusUpdate::_internal_status() const {
  return static_cast< ::TrialStatus >(_impl_.status_);
}
inline ::TrialStatus TrialStatusUpdate::status() const {
  // @@protoc_insertion_point(field_get:TrialStatusUpdate.status)
  return _internal_status();
}
inline void TrialStatusUpdate::_internal_set_status(::TrialStatus value) {
  
  _impl_.status_ = value;
}
inline void TrialStatusUpdate::set_status(::TrialStatus value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:TrialStatusUpdate.status)
}

// string message = 2;
inline void TrialStatusUpdate::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& TrialStatusUpdate::message() const {
  // @@protoc_insertion_point(field_get:TrialStatusUpdate.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TrialStatusUpdate::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TrialStatusUpdate.message)
}
inline std::string* TrialStatusUpdate::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:TrialStatusUpdate.message)
  return _s;
}
inline const std::string& TrialStatusUpdate::_internal_message() const {
  return _impl_.message_.Get();
}
inline void TrialStatusUpdate::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* TrialStatusUpdate::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* TrialStatusUpdate::release_message() {
  // @@protoc_insertion_point(field_release:TrialStatusUpdate.message)
  return _impl_.message_.Release();
}
inline void TrialStatusUpdate::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TrialStatusUpdate.message)
}

// -------------------------------------------------------------------

// TrialDataPoint

// double timestamp = 1;
inline void TrialDataPoint::clear_timestamp() {
  _impl_.timestamp_ = 0;
}
inline double TrialDataPoint::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline double TrialDataPoint::timestamp() const {
  // @@protoc_insertion_point(field_get:TrialDataPoint.timestamp)
  return _internal_timestamp();
}
inline void TrialDataPoint::_internal_set_timestamp(double value) {
  
  _impl_.timestamp_ = value;
}
inline void TrialDataPoint::set_timestamp(double value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:TrialDataPoint.timestamp)
}

// .Vector3 devicePosition = 2;
inline bool TrialDataPoint::_internal_has_deviceposition() const {
  return this != internal_default_instance() && _impl_.deviceposition_ != nullptr;
}
inline bool TrialDataPoint::has_deviceposition() const {
  return _internal_has_deviceposition();
}
inline void TrialDataPoint::clear_deviceposition() {
  if (GetArenaForAllocation() == nullptr && _impl_.deviceposition_ != nullptr) {
    delete _impl_.deviceposition_;
  }
  _impl_.deviceposition_ = nullptr;
}
inline const ::Vector3& TrialDataPoint::_internal_deviceposition() const {
  const ::Vector3* p = _impl_.deviceposition_;
  return p != nullptr ? *p : reinterpret_cast<const ::Vector3&>(
      ::_Vector3_default_instance_);
}
inline const ::Vector3& TrialDataPoint::deviceposition() const {
  // @@protoc_insertion_point(field_get:TrialDataPoint.devicePosition)
  return _internal_deviceposition();
}
inline void TrialDataPoint::unsafe_arena_set_allocated_deviceposition(
    ::Vector3* deviceposition) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.deviceposition_);
  }
  _impl_.deviceposition_ = deviceposition;
  if (deviceposition) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:TrialDataPoint.devicePosition)
}
inline ::Vector3* TrialDataPoint::release_deviceposition() {
  
  ::Vector3* temp = _impl_.deviceposition_;
  _impl_.deviceposition_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Vector3* TrialDataPoint::unsafe_arena_release_deviceposition() {
  // @@protoc_insertion_point(field_release:TrialDataPoint.devicePosition)
  
  ::Vector3* temp = _impl_.deviceposition_;
  _impl_.deviceposition_ = nullptr;
  return temp;
}
inline ::Vector3* TrialDataPoint::_internal_mutable_deviceposition() {
  
  if (_impl_.deviceposition_ == nullptr) {
    auto* p = CreateMaybeMessage<::Vector3>(GetArenaForAllocation());
    _impl_.deviceposition_ = p;
  }
  return _impl_.deviceposition_;
}
inline ::Vector3* TrialDataPoint::mutable_deviceposition() {
  ::Vector3* _msg = _internal_mutable_deviceposition();
  // @@protoc_insertion_point(field_mutable:TrialDataPoint.devicePosition)
  return _msg;
}
inline void TrialDataPoint::set_allocated_deviceposition(::Vector3* deviceposition) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.deviceposition_;
  }
  if (deviceposition) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(deviceposition);
    if (message_arena != submessage_arena) {
      deviceposition = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, deviceposition, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.deviceposition_ = deviceposition;
  // @@protoc_insertion_point(field_set_allocated:TrialDataPoint.devicePosition)
}

// .Vector3 proxyPosition = 3;
inline bool TrialDataPoint::_internal_has_proxyposition() const {
  return this != internal_default_instance() && _impl_.proxyposition_ != nullptr;
}
inline bool TrialDataPoint::has_proxyposition() const {
  return _internal_has_proxyposition();
}
inline void TrialDataPoint::clear_proxyposition() {
  if (GetArenaForAllocation() == nullptr && _impl_.proxyposition_ != nullptr) {
    delete _impl_.proxyposition_;
  }
  _impl_.proxyposition_ = nullptr;
}
inline const ::Vector3& TrialDataPoint::_internal_proxyposition() const {
  const ::Vector3* p = _impl_.proxyposition_;
  return p != nullptr ? *p : reinterpret_cast<const ::Vector3&>(
      ::_Vector3_default_instance_);
}
inline const ::Vector3& TrialDataPoint::proxyposition() const {
  // @@protoc_insertion_point(field_get:TrialDataPoint.proxyPosition)
  return _internal_proxyposition();
}
inline void TrialDataPoint::unsafe_arena_set_allocated_proxyposition(
    ::Vector3* proxyposition) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.proxyposition_);
  }
  _impl_.proxyposition_ = proxyposition;
  if (proxyposition) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:TrialDataPoint.proxyPosition)
}
inline ::Vector3* TrialDataPoint::release_proxyposition() {
  
  ::Vector3* temp = _impl_.proxyposition_;
  _impl_.proxyposition_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Vector3* TrialDataPoint::unsafe_arena_release_proxyposition() {
  // @@protoc_insertion_point(field_release:TrialDataPoint.proxyPosition)
  
  ::Vector3* temp = _impl_.proxyposition_;
  _impl_.proxyposition_ = nullptr;
  return temp;
}
inline ::Vector3* TrialDataPoint::_internal_mutable_proxyposition() {
  
  if (_impl_.proxyposition_ == nullptr) {
    auto* p = CreateMaybeMessage<::Vector3>(GetArenaForAllocation());
    _impl_.proxyposition_ = p;
  }
  return _impl_.proxyposition_;
}
inline ::Vector3* TrialDataPoint::mutable_proxyposition() {
  ::Vector3* _msg = _internal_mutable_proxyposition();
  // @@protoc_insertion_point(field_mutable:TrialDataPoint.proxyPosition)
  return _msg;
}
inline void TrialDataPoint::set_allocated_proxyposition(::Vector3* proxyposition) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.proxyposition_;
  }
  if (proxyposition) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(proxyposition);
    if (message_arena != submessage_arena) {
      proxyposition = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, proxyposition, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.proxyposition_ = proxyposition;
  // @@protoc_insertion_point(field_set_allocated:TrialDataPoint.proxyPosition)
}

// .Vector3 force = 4;
inline bool TrialDataPoint::_internal_has_force() const {
  return this != internal_default_instance() && _impl_.force_ != nullptr;
}
inline bool TrialDataPoint::has_force() const {
  return _internal_has_force();
}
inline void TrialDataPoint::clear_force() {
  if (GetArenaForAllocation() == nullptr && _impl_.force_ != nullptr) {
    delete _impl_.force_;
  }
  _impl_.force_ = nullptr;
}
inline const ::Vector3& TrialDataPoint::_internal_force() const {
  const ::Vector3* p = _impl_.force_;
  return p != nullptr ? *p : reinterpret_cast<const ::Vector3&>(
      ::_Vector3_default_instance_);
}
inline const ::Vector3& TrialDataPoint::force() const {
  // @@protoc_insertion_point(field_get:TrialDataPoint.force)
  return _internal_force();
}
inline void TrialDataPoint::unsafe_arena_set_allocated_force(
    ::Vector3* force) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.force_);
  }
  _impl_.force_ = force;
  if (force) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:TrialDataPoint.force)
}
inline ::Vector3* TrialDataPoint::release_force() {
  
  ::Vector3* temp = _impl_.force_;
  _impl_.force_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Vector3* TrialDataPoint::unsafe_arena_release_force() {
  // @@protoc_insertion_point(field_release:TrialDataPoint.force)
  
  ::Vector3* temp = _impl_.force_;
  _impl_.force_ = nullptr;
  return temp;
}
inline ::Vector3* TrialDataPoint::_internal_mutable_force() {
  
  if (_impl_.force_ == nullptr) {
    auto* p = CreateMaybeMessage<::Vector3>(GetArenaForAllocation());
    _impl_.force_ = p;
  }
  return _impl_.force_;
}
inline ::Vector3* TrialDataPoint::mutable_force() {
  ::Vector3* _msg = _internal_mutable_force();
  // @@protoc_insertion_point(field_mutable:TrialDataPoint.force)
  return _msg;
}
inline void TrialDataPoint::set_allocated_force(::Vector3* force) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.force_;
  }
  if (force) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(force);
    if (message_arena != submessage_arena) {
      force = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, force, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.force_ = force;
  // @@protoc_insertion_point(field_set_allocated:TrialDataPoint.force)
}

// -------------------------------------------------------------------

// Color

// double r = 1;
inline void Color::clear_r() {
  _impl_.r_ = 0;
}
inline double Color::_internal_r() const {
  return _impl_.r_;
}
inline double Color::r() const {
  // @@protoc_insertion_point(field_get:Color.r)
  return _internal_r();
}
inline void Color::_internal_set_r(double value) {
  
  _impl_.r_ = value;
}
inline void Color::set_r(double value) {
  _internal_set_r(value);
  // @@protoc_insertion_point(field_set:Color.r)
}

// double g = 2;
inline void Color::clear_g() {
  _impl_.g_ = 0;
}
inline double Color::_internal_g() const {
  return _impl_.g_;
}
inline double Color::g() const {
  // @@protoc_insertion_point(field_get:Color.g)
  return _internal_g();
}
inline void Color::_internal_set_g(double value) {
  
  _impl_.g_ = value;
}
inline void Color::set_g(double value) {
  _internal_set_g(value);
  // @@protoc_insertion_point(field_set:Color.g)
}

// double b = 3;
inline void Color::clear_b() {
  _impl_.b_ = 0;
}
inline double Color::_internal_b() const {
  return _impl_.b_;
}
inline double Color::b() const {
  // @@protoc_insertion_point(field_get:Color.b)
  return _internal_b();
}
inline void Color::_internal_set_b(double value) {
  
  _impl_.b_ = value;
}
inline void Color::set_b(double value) {
  _internal_set_b(value);
  // @@protoc_insertion_point(field_set:Color.b)
}

// -------------------------------------------------------------------

// Vector3

// double x = 1;
inline void Vector3::clear_x() {
  _impl_.x_ = 0;
}
inline double Vector3::_internal_x() const {
  return _impl_.x_;
}
inline double Vector3::x() const {
  // @@protoc_insertion_point(field_get:Vector3.x)
  return _internal_x();
}
inline void Vector3::_internal_set_x(double value) {
  
  _impl_.x_ = value;
}
inline void Vector3::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Vector3.x)
}

// double y = 2;
inline void Vector3::clear_y() {
  _impl_.y_ = 0;
}
inline double Vector3::_internal_y() const {
  return _impl_.y_;
}
inline double Vector3::y() const {
  // @@protoc_insertion_point(field_get:Vector3.y)
  return _internal_y();
}
inline void Vector3::_internal_set_y(double value) {
  
  _impl_.y_ = value;
}
inline void Vector3::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Vector3.y)
}

// double z = 3;
inline void Vector3::clear_z() {
  _impl_.z_ = 0;
}
inline double Vector3::_internal_z() const {
  return _impl_.z_;
}
inline double Vector3::z() const {
  // @@protoc_insertion_point(field_get:Vector3.z)
  return _internal_z();
}
inline void Vector3::_internal_set_z(double value) {
  
  _impl_.z_ = value;
}
inline void Vector3::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Vector3.z)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::TrialStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::TrialStatus>() {
  return ::TrialStatus_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_franka_5ftrial_2eproto
