// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: franka_trial.proto
#ifndef GRPC_franka_5ftrial_2eproto__INCLUDED
#define GRPC_franka_5ftrial_2eproto__INCLUDED

#include "franka_trial.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class FrankaTrialService final {
 public:
  static constexpr char const* service_full_name() {
    return "FrankaTrialService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::TrialResponseStream>> RunTrial(::grpc::ClientContext* context, const ::TrialRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::TrialResponseStream>>(RunTrialRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::TrialResponseStream>> AsyncRunTrial(::grpc::ClientContext* context, const ::TrialRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::TrialResponseStream>>(AsyncRunTrialRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::TrialResponseStream>> PrepareAsyncRunTrial(::grpc::ClientContext* context, const ::TrialRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::TrialResponseStream>>(PrepareAsyncRunTrialRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RunTrial(::grpc::ClientContext* context, const ::TrialRequest* request, ::grpc::ClientReadReactor< ::TrialResponseStream>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::TrialResponseStream>* RunTrialRaw(::grpc::ClientContext* context, const ::TrialRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::TrialResponseStream>* AsyncRunTrialRaw(::grpc::ClientContext* context, const ::TrialRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::TrialResponseStream>* PrepareAsyncRunTrialRaw(::grpc::ClientContext* context, const ::TrialRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::TrialResponseStream>> RunTrial(::grpc::ClientContext* context, const ::TrialRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::TrialResponseStream>>(RunTrialRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::TrialResponseStream>> AsyncRunTrial(::grpc::ClientContext* context, const ::TrialRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::TrialResponseStream>>(AsyncRunTrialRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::TrialResponseStream>> PrepareAsyncRunTrial(::grpc::ClientContext* context, const ::TrialRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::TrialResponseStream>>(PrepareAsyncRunTrialRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RunTrial(::grpc::ClientContext* context, const ::TrialRequest* request, ::grpc::ClientReadReactor< ::TrialResponseStream>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::TrialResponseStream>* RunTrialRaw(::grpc::ClientContext* context, const ::TrialRequest& request) override;
    ::grpc::ClientAsyncReader< ::TrialResponseStream>* AsyncRunTrialRaw(::grpc::ClientContext* context, const ::TrialRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::TrialResponseStream>* PrepareAsyncRunTrialRaw(::grpc::ClientContext* context, const ::TrialRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RunTrial_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RunTrial(::grpc::ServerContext* context, const ::TrialRequest* request, ::grpc::ServerWriter< ::TrialResponseStream>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_RunTrial : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RunTrial() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RunTrial() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunTrial(::grpc::ServerContext* /*context*/, const ::TrialRequest* /*request*/, ::grpc::ServerWriter< ::TrialResponseStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRunTrial(::grpc::ServerContext* context, ::TrialRequest* request, ::grpc::ServerAsyncWriter< ::TrialResponseStream>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RunTrial<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RunTrial : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RunTrial() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::TrialRequest, ::TrialResponseStream>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::TrialRequest* request) { return this->RunTrial(context, request); }));
    }
    ~WithCallbackMethod_RunTrial() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunTrial(::grpc::ServerContext* /*context*/, const ::TrialRequest* /*request*/, ::grpc::ServerWriter< ::TrialResponseStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::TrialResponseStream>* RunTrial(
      ::grpc::CallbackServerContext* /*context*/, const ::TrialRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RunTrial<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RunTrial : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RunTrial() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RunTrial() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunTrial(::grpc::ServerContext* /*context*/, const ::TrialRequest* /*request*/, ::grpc::ServerWriter< ::TrialResponseStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RunTrial : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RunTrial() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RunTrial() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunTrial(::grpc::ServerContext* /*context*/, const ::TrialRequest* /*request*/, ::grpc::ServerWriter< ::TrialResponseStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRunTrial(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RunTrial : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RunTrial() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->RunTrial(context, request); }));
    }
    ~WithRawCallbackMethod_RunTrial() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunTrial(::grpc::ServerContext* /*context*/, const ::TrialRequest* /*request*/, ::grpc::ServerWriter< ::TrialResponseStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* RunTrial(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_RunTrial : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_RunTrial() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::TrialRequest, ::TrialResponseStream>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::TrialRequest, ::TrialResponseStream>* streamer) {
                       return this->StreamedRunTrial(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_RunTrial() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RunTrial(::grpc::ServerContext* /*context*/, const ::TrialRequest* /*request*/, ::grpc::ServerWriter< ::TrialResponseStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedRunTrial(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::TrialRequest,::TrialResponseStream>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_RunTrial<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_RunTrial<Service > StreamedService;
};


#endif  // GRPC_franka_5ftrial_2eproto__INCLUDED
